# Generated by Django 4.2.14 on 2024-08-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0060_partially_populate_availability"),
        ("channels", "0015_channel_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="featured_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel",
                to="learning_resources.learningresource",
            ),
        ),
    ]
